- name: playbook for git
  hosts: vagrant
  sudo: True
  vars:
     database_name: ansible
     database_user: ansible
     local: local
     
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=0 state=present force=yes 
      sudo: True
      with_items:
         - git
         - libjpeg-dev
         - libpq-dev
         - memcached
         - nginx
         - postgresql
         - python-dev
         - python-pip
         - python-psycopg2
         - python-setuptools
         - python-virtualenv
         - supervisor
      
    - name: create the a user 
      postgresql_user: 
             name: ansible 
             password: ansible
      sudo: True
      sudo_user: postgres 
      




